### ISSUE TITLE
synergysportstech registered member

### ISSUE THREAD

**Issue by leeprinxin** [JoshWeiner/NBA_Game_Prediction#4]
I would like to get the latest competition data and therefore have to run the crawl through the Colab notes you provided, but the synergysportstech website requires a membership login to run the subsequent operations.
I tried to find the site but couldn't find the registered member function, how did you register the member?

**Comment by JoshWeiner** [comment]
We accessed data from Synergy Sports with funding from the University of Pennsylvania. They, through their Division 1 athletic programs had signed a contract with Synergy Sports through which we also received access.
As an unfortunate consequence of this, we are not at liberty to provide public access to our dataset- nor is it straightforward to create an account as an individual. 

However, we have compiled a list of alternative datasets through which one can replicate and improve upon our data:
https://www.basketball-reference.com/leagues/
https://www.kaggle.com/datasets/wyattowalsh/basketball
https://www.kaggle.com/datasets/nathanlauga/nba-games
https://www.kaggle.com/datasets/drgilermo/nba-players-stats
